export const projectConstants = {
    GET_PROJECT_REQUEST : "GET_PROJECT_REQUEST",
    GET_PROJECT_SUCCESS : "GET_PROJECT_SUCCESS",
    GET_PROJECT_FAILURE : "GET_PROJECT_FAILURE",
    GET_PROJECT_BY_SLUG_REQUEST : "GET_PROJECT_BY_SLUG_REQUEST",
    GET_PROJECT_BY_SLUG_SUCCESS : "GET_PROJECT_BY_SLUG_SUCCESS",
    GET_PROJECT_BY_SLUG_FAILURE : "GET_PROJECT_BY_SLUG_FAILURE"
}

export const projectCategoriesConstants = {
    GET_PROJECT_CATEGORIES_REQUEST : "GET_PROJECT_CATEGORIES_REQUEST",
    GET_PROJECT_CATEGORIES_SUCCESS : "GET_PROJECT_CATEGORIES_SUCCESS",
    GET_PROJECT_CATEGORIES_FAILURE : "GET_PROJECT_CATEGORIES_FAILURE",
    GET_PROJECT_CATEGORY_REQUEST : "GET_PROJECT_CATEGORY_REQUEST",
    GET_PROJECT_CATEGORY_SUCCESS : "GET_PROJECT_CATEGORY_SUCCESS",
    GET_PROJECT_CATEGORY_FAILURE : "GET_PROJECT_CATEGORY_FAILURE",
    GET_PROJECT_CATEGORY_BY_PROJECT_SLUG_REQUEST : "GET_PROJECT_CATEGORY_BY_PROJECT_SLUG_REQUEST",
    GET_PROJECT_CATEGORY_BY_PROJECT_SLUG_SUCCESS : "GET_PROJECT_CATEGORY_BY_PROJECT_SLUG_SUCCESS",
    GET_PROJECT_CATEGORY_BY_PROJECT_SLUG_FAILURE : "GET_PROJECT_CATEGORY_BY_PROJECT_SLUG_FAILURE",
}

export const resumeConstants = {
    GET_RESUME_REQUEST : "GET_RESUME_REQUEST",
    GET_RESUME_SUCCESS : "GET_RESUME_SUCCESS",
    GET_RESUME_FAILURE : "GET_RESUME_FAILURE"
}
